spring.application.name=inventario

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/inventarioDB}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:changeme}
